"""drop Null columns

Revision ID: 7d2d363433b5
Revises: dd73dca2c884
Create Date: 2023-05-20 11:53:58.381200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2d363433b5'
down_revision = 'dd73dca2c884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'planes')
    op.drop_column('planes', 'route')
    op.drop_column('planes', 'airline')
    op.drop_column('routes', 'planes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('planes', sa.VARCHAR(), nullable=True))
    op.add_column('planes', sa.Column('airline', sa.VARCHAR(), nullable=True))
    op.add_column('planes', sa.Column('route', sa.VARCHAR(), nullable=True))
    op.add_column('airlines', sa.Column('planes', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
