"""add passengers

Revision ID: d83123a9902a
Revises: eb716b6a9f09
Create Date: 2023-05-20 11:00:56.609249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83123a9902a'
down_revision = 'eb716b6a9f09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=True),
    sa.Column('passenger_age', sa.Integer(), nullable=True),
    sa.Column('plane_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plane_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    # ### end Alembic commands ###
